name: makhber
summary: Makhber
description: |
  Application for Visualization and Analysis of Scientific Data
license: GPL-2.0-or-later
type: app
icon: packaging/freedesktop/com.github.makhber.Makhber.svg
website: https://github.com/Makhber/makhber
issues: https://github.com/Makhber/makhber/issues
base: core22
compression: lzo
grade: stable
confinement: strict
adopt-info: makhber
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64el
  - build-on: s390x

apps:
  makhber:
    common-id: com.github.makhber.Makhber
    command: bin/desktop-launch $SNAP/usr/bin/makhber
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs:
      - home
      - network
      - removable-media
      - unity7
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11

parts:
  makhber:
    source-type: local
    source: .
    parse-info: [usr/share/metainfo/com.github.makhber.Makhber.appdata.xml]
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DBUILD_SHARED_LIBS=ON"
      - "-DMAKHBER_SCRIPTING_PYTHON=ON"
      - "-DMAKHBER_SEARCH_FOR_UPDATES=OFF"
      - "-DCMAKE_PREFIX_PATH=$CRAFT_STAGE/usr"
    build-environment:
      - PATH: $HOME/.local/bin:$PATH
      - PYTHONPATH: $CRAFT_STAGE/usr/lib/python3/dist-packages:$HOME/.local/lib/python3.10/site-packages:/usr/local/lib/python3.10/dist-packages:/usr/lib/python3/dist-packages
    build-packages:
      - g++
      - git
      - libqt6svg6-dev
      - libqt6opengl6-dev
      - qt6-l10n-tools
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - pkgconf
      - libxkbcommon-dev
      - libvulkan-dev
      - libglu1-mesa-dev
    stage-packages:
      - libglu1-mesa
      - libpython3.10
      - libqt6svg6
      - libqt6openglwidgets6
      - libqt6printsupport6
      - qt6-translations-l10n
      - qt6-wayland
      - qt6-qpa-plugins
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags)"
    after:
      - desktop-qt6
      - gsl
      - muparser
      - qwt
      - gl2ps
      - pyqt6
      - pyqt6-sip
  desktop-qt6:
    source: https://github.com/MehdiChinoune/snapcraft-desktop-helpers.git
    source-branch: qt6
    source-subdir: qt
    plugin: make
    make-parameters: ["QT_VERSION=6"]
  gsl:
    source-type: tar
    source: https://ftp.gnu.org/gnu/gsl/gsl-2.7.1.tar.gz
    source-checksum: sha256/dcb0fbd43048832b757ff9942691a8dd70026d5da0ff85601e52687f6deeb34b
    plugin: autotools
    autotools-configure-parameters:
      - "--disable-static"
      - "--prefix=/usr"
    build-packages:
      - g++
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/*.la
      - -usr/lib/pkgconfig
      - -usr/share
  muparser:
    source-type: tar
    source: https://github.com/beltoforion/muparser/archive/v2.3.4.tar.gz
    source-checksum: sha256/0c3fa54a3ebf36dda0ed3e7cd5451c964afbb15102bdbcba08aafb359a290121
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-packages:
      - g++
    stage-packages:
      - libgomp1
    prime:
      - -usr/include
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake
      - -usr/share
  qwt:
    source-type: tar
    source: https://downloads.sourceforge.net/qwt/qwt-6.2.0.tar.bz2
    source-checksum: sha256/9194f6513955d0fd7300f67158175064460197abab1a92fa127a67a4b0b71530
    plugin: make
    build-packages:
      - g++
      - libgles-dev
    stage-packages:
      - libqt6svg6
      - libqt6opengl6
    override-build: |
      sed -i "s|^\\s*QWT_INSTALL_PREFIX.*$|QWT_INSTALL_PREFIX=$CRAFT_PART_INSTALL/usr|g" qwtconfig.pri
      sed -i "s|^QWT_CONFIG\\s*+=\\s*QwtDesigner$|#|g" qwtconfig.pri
      sed -i "s|^QWT_CONFIG\\s*+=\\s*QwtExamples$|#|g" qwtconfig.pri
      sed -i "s|^QWT_CONFIG\\s*+=\\s*QwtPlayground$|#|g" qwtconfig.pri
      sed -i "s|^QWT_CONFIG\\s*+=\\s*QwtTests$|#|g" qwtconfig.pri
      qmake6 \
        CONFIG-=debug_and_release \
        CONFIG+=release \
        qwt.pro
      craftctl default
    prime:
      - -usr/lib/pkgconfig
      - -usr/include
      - -usr/doc
      - -usr/features
  gl2ps:
    source-type: tar
    source: https://geuz.org/gl2ps/src/gl2ps-1.4.2.tgz
    source-checksum: sha256/8d1c00c1018f96b4b97655482e57dcb0ce42ae2f1d349cd6d4191e7848d9ffe9
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-packages:
      - g++
    stage-packages:
      - libgl1
      - libpng16-16
    prime:
      - -usr/lib/libgl2ps.a
      - -usr/include
      - -usr/share
  pyqt6:
    source-type: tar
    source: https://pypi.python.org/packages/source/P/PyQt6/PyQt6-6.7.0.tar.gz
    source-checksum: sha256/3d31b2c59dc378ee26e16586d9469842483588142fc377280aad22aaf2fa6235
    plugin: make
    build-packages:
      - g++
      - libgl-dev
      - libgles-dev
      - libpython3-dev
      - python3-pip
    stage-packages:
      - libqt6svg6
      - libqt6opengl6
      - libqt6printsupport6
    build-environment:
      - PATH: $HOME/.local/bin:$PATH
    override-build: |
      pip3 install sip pyqt-builder
      cd $CRAFT_PART_SRC
      sip-build --confirm-license \
        --build-dir ../build \
        --target-dir $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages \
        --qmake=/usr/bin/qmake6 \
        --no-make \
        --no-tools \
        --no-designer-plugin \
        --no-qml-plugin \
        --disable QtBluetooth \
        --disable QtDBus \
        --disable QtDesigner \
        --disable QtHelp \
        --disable QtMultimedia \
        --disable QtMultimediaWidgets \
        --disable QtNfc \
        --disable QtPositioning \
        --disable QtQml \
        --disable QtQuick \
        --disable QtQuick3D \
        --disable QtQuickWidgets \
        --disable QtRemoteObjects \
        --disable QtSensors \
        --disable QtSerialPort \
        --disable QtSql \
        --disable QtSvgWidgets \
        --disable QtTest \
        --disable QtWebChannel \
        --disable QtWebSockets \
        --disable QtXml \
        --verbose
      cd $CRAFT_PART_BUILD
      craftctl default
    prime:
      - -usr/lib/python3/dist-packages/PyQt6/bindings
  pyqt6-sip:
    plugin: nil
    build-packages:
      - python3-pip
    override-build:
      pip3 install pyqt6-sip --no-deps --target=$CRAFT_PART_INSTALL/usr/lib/python3/dist-packages
